# ----------------------------#
#        JAVA BUILD           #
# ----------------------------#
FROM maven:3.6-jdk-11 AS build

RUN mkdir /app

# Install dependencies of Lib
RUN mkdir -p /app/libs

COPY awardslibs/pom.xml /app/libs/pom.xml

WORKDIR /app/libs/

ENV MVN="mvn -B -s /usr/share/maven/ref/settings-docker.xml"
RUN $MVN --version

# Expected to download dependencies but not build
RUN $MVN dependency:go-offline

COPY awardslibs/src /app/libs/src

# Build and install libs
RUN $MVN -f pom.xml clean install -DskipTests

#------------------------- LIBS BUILD COMPLETE ---------------------#

WORKDIR /app

# Install dependencies of module
RUN mkdir -p /app/module

COPY wwwservice/pom.xml /app/module/

WORKDIR /app/module/

# Expected to download dependencies but not build
RUN $MVN dependency:go-offline

COPY wwwservice/src /app/module/src

# Build now
RUN $MVN -f pom.xml clean package -DskipTests

# -------------------------------#
#        JAVA Service            #
# -------------------------------#
FROM openjdk:11

COPY --from=build /usr/share/maven/ref/repository/com/metrix  /root/.m2/repository/com/metrix

# Copy the built service jars and resources
COPY --from=build /app/module/target/WwwService.jar WwwService.jar

ENTRYPOINT ["java","-jar","WwwService.jar"]


